name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Lab2.sln
      Test_Project_Path: ICT3101_Calculator.UnitTests/

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build Solution
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore

    - name: NUnit Tests
      working-directory: ICT3101_Calculator.UnitTests/
      run: dotnet test --no-build --verbosity normal

    - name: SpecFlow Tests
      working-directory: SpecFlowCalculatorTests/
      run: dotnet test --no-build --verbosity normal

